from scapy.all import *
from c1222_classes import *

def createMessageFromService(serviceIn):
    message = Message(
        pdus=[
            AscePdu(
                tag=1,
                len=LengthType(
                    num=5,
                    islong=0
                ),
                elements=[
                    Element(
                        tag=AsceElementTags.CALLED_AP_TITLE.value,
                        calledApTitle=CalledAPTitle(
                            len=0,
                            apTitle=ID(
                                tag=2,
                                len=0
                            )
                        )
                    ),
                    Element(
                        tag=AsceElementTags.CALLING_AP_TITLE.value,
                        callingApTitle=CallingAPTitle(
                            len=0,
                            apTitle=ID(
                                tag=3,
                                len=0
                            )
                        )
                    ),
                    Element(
                        tag=AsceElementTags.CALLING_AP_INVOCATION_ID.value,
                        callingApInvocationId=CallingAPInvocationID(
                            len=LengthType(
                                num=0,
                                islong=0
                            ),
                            intTag=0,
                            idLen=LengthType(
                                num=0,
                                islong=0
                            ),
                            id=""
                        )
                    ),
                    Element(
                        tag=AsceElementTags.CALLING_AUTHENTICATION_VALUE.value,
                        callingAuthenticationValue=CallingAuthenticationValue(
                            len=LengthType(
                                num=0,
                                islong=0
                            ),
                            externalTag=0,
                            externalLen=LengthType(
                                num=0,
                                islong=0
                            ),
                            indirectReference=CAVIndirectRef(
                                a=0,
                                b=0,
                                c=0
                            ),
                            encodingTag=0xA0,
                            singleAsn1=CAVSingleAsn1(
                                len=LengthType(
                                    num=0,
                                    islong=0
                                ),
                                mechanismTag=0,
                                c1222Encoding=CallingAuthValC1222(
                                    len=LengthType(
                                        num=0,
                                        islong=0
                                    ),
                                    keyId=KeyID(
                                        tag=0,
                                        len=LengthType(
                                            num=0,
                                            islong=0
                                        ),
                                        keyId=0
                                    ),
                                    iv=IV(
                                        tag=0,
                                        len=LengthType(
                                            num=0,
                                            islong=0
                                        ),
                                        iv=0
                                    )
                                ),
                                c1221Encoding=CallingAuthValC1221(
                                    len=LengthType(
                                        num=0,
                                        islong=0
                                    ),
                                    msg=0,
                                    # probably need other stuff here
                                )
                            )
                        )
                    ),
                    Element(
                        tag=AsceElementTags.USER_INFORMATION.value,
                        userInformation=UserInformation(
                            externalLen=LengthType(
                                num=0,
                                islong=0
                            ),
                            externalTag=0,
                            len=LengthType(
                                num=0,
                                islong=0
                            ),
                            indirectReference=UserIndirectRef(
                                tag=0,
                                len=LengthType(
                                    num=0,
                                    islong=0
                                ),
                                encoding=0
                            ),
                            octetTag=0,
                            userInfoLen=LengthType(
                                num=100,
                                islong=0
                            ),
                            epsem=Epsem(
                                #epsemControl=0,
                                data=PlaintextEpsem(
                                    data=[
                                        EpsemService(
                                            len=LengthType(
                                                num=0,
                                                islong=0
                                            ),
                                            service=serviceIn
                                        )
                                    ]
                                )
                            )
                        )
                    ),
                ]
            )
        ]
    )

    return message;